## SVM using hearing_test dataset

In [1]:
# import the required packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# prerequisities

import warnings
warnings.filterwarnings(action="ignore")

In [3]:
df=pd.read_csv("hearing_test.csv")
df.head()

    age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [4]:
df.describe()

               age  physical_score  test_result
count  5000.000000     5000.000000  5000.000000
mean     51.609000       32.760260     0.600000
std      11.287001        8.169802     0.489947
min      18.000000       -0.000000     0.000000
25%      43.000000       26.700000     0.000000
50%      51.000000       35.300000     1.000000
75%      60.000000       38.900000     1.000000
max      90.000000       50.000000     1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   float64
 1   physical_score  5000 non-null   float64
 2   test_result     5000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

In [6]:
df.corr()

                     age  physical_score  test_result
age             1.000000       -0.782146    -0.683171
physical_score -0.782146        1.000000     0.792716
test_result    -0.683171        0.792716     1.000000

In [7]:
# create x
x=df.drop(['test_result'],axis=1)

#creat y
y=df['test_result']

In [8]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=123456)

In [9]:
from sklearn.svm import SVC
# SVC - Support Vector Classifier

model=SVC()

model.fit(x_train,y_train)

SVC()

In [10]:
y_pred =model.predict(x_test)

In [11]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

accuracy= accuracy_score(y_test,y_pred)
precision= precision_score(y_test,y_pred)
recall= recall_score(y_test,y_pred)
f1= f1_score(y_test,y_pred)

print(f"Accuracy ={accuracy}")
print(f"Precision ={precision}")
print(f"Recall ={recall}")
print(f"F1 Score ={f1}")

Accuracy =0.923
Precision =0.9140625
Recall =0.9637561779242174
F1 Score =0.9382518043303929

In [ ]:
# visualize the data