## Read the csv file and add a column

In [1]:
# import the required packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the dataset
df=pd.read_csv("Salary_Data.csv")
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

## EDA

In [4]:
# display first 5 records of dataset
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [5]:
# display last 5 records of dataset
df.tail()

    YearsExperience  Salary
28             10.3  122391
29             10.5  121872
30             11.0  140000
31             12.0  155000
32             13.0  156000

In [6]:
# know the statistical information about the dataset
df.describe()

       YearsExperience         Salary
count        33.000000      33.000000
mean          5.921212   82760.303030
std           3.342413   34014.620992
min           1.100000   37731.000000
25%           3.200000   56957.000000
50%           5.100000   67938.000000
75%           8.700000  109431.000000
max          13.000000  156000.000000

In [7]:
# basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  33 non-null     float64
 1   Salary           33 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 656.0 bytes

In [8]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')