## Shuffle and dividing the data into train and test split

In [1]:
# import the required packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings(action="ignore")

In [3]:
df=pd.read_csv("hearing_test.csv")
df.head()

    age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [4]:
df.describe()

               age  physical_score  test_result
count  5000.000000     5000.000000  5000.000000
mean     51.609000       32.760260     0.600000
std      11.287001        8.169802     0.489947
min      18.000000       -0.000000     0.000000
25%      43.000000       26.700000     0.000000
50%      51.000000       35.300000     1.000000
75%      60.000000       38.900000     1.000000
max      90.000000       50.000000     1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   float64
 1   physical_score  5000 non-null   float64
 2   test_result     5000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

## Preprocessing of Data

In [6]:
# split the data into x and y
x=df.drop('test_result',axis=1)
y=df['test_result']

## split the data into train and test

In [7]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,shuffle=True,random_state=123456)

In [8]:
x_train

       age  physical_score
2537  79.0            10.2
1175  43.0            36.9
485   41.0            39.6
3651  51.0            36.4
4618  52.0            36.1
...    ...             ...
2799  60.0            21.2
171   44.0            28.3
3640  46.0            40.0
3121  47.0            38.1
4594  50.0            33.6

[3500 rows x 2 columns]

In [9]:
x_test

       age  physical_score
4158  46.0            38.1
2117  47.0            35.1
3328  49.0            37.0
4813  40.0            37.7
4176  35.0            42.0
...    ...             ...
4948  45.0            35.6
3009  55.0            29.6
4447  47.0            38.0
1083  49.0            38.2
3487  59.0            25.3

[1500 rows x 2 columns]

In [10]:
y_test

4158    1
2117    1
3328    1
4813    1
4176    1
       ..
4948    1
3009    0
4447    1
1083    1
3487    0
Name: test_result, Length: 1500, dtype: int64