In [49]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [50]:
import warnings 

warnings.filterwarnings(action="ignore")

In [51]:
df=pd.read_csv("energy_dataset.csv")

In [52]:
df.head()

,Date,Time,Voltage,Current,Power_Consumption,Power_Factor,Frequency,Energy_Consumed,Device_Status
0,2026-03-01,08:00:00,232.4,1.91,377.30,0.85,49.89,0.744,OFF
1,2026-03-01,09:00:00,233.7,16.22,3108.30,0.82,49.97,1.739,ON
2,2026-03-01,10:00:00,217.7,9.84,1735.16,0.81,49.88,3.123,ON
3,2026-03-01,11:00:00,229.1,5.14,1071.59,0.91,50.12,0.550,ON
4,2026-03-01,12:00:00,238.2,13.02,2667.17,0.86,49.86,6.440,ON

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               100 non-null    object
 1   Time               100 non-null    object
 2   Voltage            100 non-null    float64
 3   Current            100 non-null    float64
 4   Power_Consumption  100 non-null    float64
 5   Power_Factor       100 non-null    float64
 6   Frequency          100 non-null    float64
 7   Energy_Consumed    100 non-null    float64
 8   Device_Status      100 non-null    object
dtypes: float64(6), object(3)
memory usage: 7.2+ KB

In [54]:
x = df.drop('Power consumption', axis=1, errors='ignore')

In [55]:
df.head()

,Date,Time,Voltage,Current,Power_Consumption,Power_Factor,Frequency,Energy_Consumed,Device_Status
0,2026-03-01,08:00:00,232.4,1.91,377.30,0.85,49.89,0.744,OFF
1,2026-03-01,09:00:00,233.7,16.22,3108.30,0.82,49.97,1.739,ON
2,2026-03-01,10:00:00,217.7,9.84,1735.16,0.81,49.88,3.123,ON
3,2026-03-01,11:00:00,229.1,5.14,1071.59,0.91,50.12,0.550,ON
4,2026-03-01,12:00:00,238.2,13.02,2667.17,0.86,49.86,6.440,ON

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=123456)

In [ ]:
x_train

In [56]:
from sklearn.linear_model import LinearRegression

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
model = LinearRegression()

In [65]:

x = df.drop(columns=['Power Consumption'])  
y = df['Power Consumption']                 

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

KeyError: "['Power Consumption'] not found in axis"

In [40]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

NameError: name 'accuracy_score' is not defined

In [ ]:
plt.scatter(range(len(y_test)), y_test, label="Actual")
plt.scatter(range(len(y_pred)), y_pred, label="Predicted")
plt.legend()
plt.show()